### PR TITLE
Updated: Added Support for WebP Images

### PR DESCRIPTION
**Pull request by brookinsconsulting**
Hello,

Our patches are small but powerful. I'm trying to get this feature into most of the active ezpublish forks.

Please let us know what you think.

Cheers,
Brookins Consulting

### CODE REVIEW

**Comment by brookinsconsulting** [comment]
We are also talking to mugoweb to help their fork, https://github.com/mugoweb/ezpublish-legacy/pull/212/files

**Comment by emodric** [comment]
Hi! Is this tested as working 100%? :)

**Comment by brookinsconsulting** [comment]
@emodric yes this has been tested as working with more than one installation

**Comment by emodric** [comment]
Thanks @brookinsconsulting !

**Pull request merged**
