### PR TITLE
Browse module get class error

### PR DESCRIPTION
**Pull request by brookinsconsulting**
Hello @emodric 

This pr is a bugfix for the copy view and the browse view template error that has bothered me for some time. Today fixes all that by testing for a null object before trying to get_class. Which as we all know produces a fatal error and prevents node selection.

I know i'm going fast bug I'm almost to a 100% ezpublish working on the latest php (8.2.x) with no more fatal errors. We still have a few nasty bugs generating warnings only. One is a zetacomponents/console-tools related and another is a template variable not set warning which seems to indicate something is broken with the template system (php or tpl).

Cheers,
Brookins Consulting

### CODE REVIEW

**Comment by emodric** [comment]
Hi @brookinsconsulting ! It seems that this PR now includes already merged #23 and git for some reason does not recognize this.

Can you clean this up by rebasing, otherwise, I'm worried we will get duplicated code?

**Comment by brookinsconsulting** [comment]
Yes give me a little time and I’ll rebase tonight

**Comment by brookinsconsulting** [comment]
@emodric  Time speeds up! ;) I update my branch. It should be clean for merging.

**Comment by brookinsconsulting** [comment]
Hello,
I noticed a missed tpl bug I introduced and updated this pr and branch as a result. It should be good for merging now.
Cheers,
Brookins Consulting

**Comment by emodric** [comment]
Thanks @brookinsconsulting !

**Pull request merged**
