### PR TITLE
202308 808 migrate the code to display the trashed date in the admin interface ng

### PR DESCRIPTION
**Pull request by ernestob**
This pull request updates the trash admin interface. We are adding a new column to display when the objects were trashed.

Trash_-_eZ_Publish_Demo_Site

### CODE REVIEW

**Comment by brookinsconsulting** [comment]
Thank you for your contribution!

**Comment by brookinsconsulting** [comment]
@emodric 

What must be done to merge improvements like this one for everyone to enjoy?

Cheers,
Brookins Consulting

**Comment by emodric** [comment]
@brookinsconsulting Someone to review, e.g. you, if that's okay ;) Becuase I don't have much time recently.

**Comment by brookinsconsulting** [comment]
@emodric Understood. 

@ernestob I’ll test this locally and review it in greater detail right away. Thank you for your patience and time.

Cheers,
Brookins Consulting

**Comment by se7enxweb** [comment]
This PR is lacking overall polish to the core of ezpublish. The template change is great but other changes are missing.

- [x] Missing Schema

The template causes a error on page load when installed due to the database schema missing the changes to the database to support the trashed field that is being added. @ernestob  Please add changes to the database schema to support the new field to the ezcontentobject_trash table.

- [ ] Missing Empty Date Template Logic

With this change made to the table the page loads with minimal issues. Another remaining issue is that existing eZ Publish Trashed Content Tree content lacks data in the newly added trashed field and displays the rather ugly date: 12/31/1969 06:00 pm. This might be better handled in the trash.tpl template logic to test for an empty trashed date before displaying it. Alternatively it could display the text 'Undocumented' instead of the ugly date when trashed date content is empty.

- [ ] Missing Public Variables

The debug output lists one new error that must be fixed for php9 compatibility. 
Classes eZContentObjectTrashNode and eZPersistentObject must both be modified to address this php 8.2 warning.
Just add the missing public property to both classes to fix this warning. @ernestob Please fix this as well.

Creation of dynamic property eZContentObjectTrashNode::$Trashed is deprecated in /web/vh/demo.se7enx.com/demo.se7enx.com/kernel/classes/ezpersistentobject.php on line 92

- [ ] Missing Trashed Field Population Code 

Perhaps lastly we need some php code added into ezpublish content systems to populate the trashed field in the content object upon removal and storage in the trash system. @ernestob This also seems to be a key missing feature of your PR. To be able to accept it we will need more work to avoid breaking anyone's existing eZ Publish installations.

Thank you for your continued support.

Respectfully,
7x
(Formerly Brookins Consulting)

**Comment by se7enxweb** [comment]
@ernestob Appologies after closer review I found the database modification sql in the upgrade scripts.

And I can take care of most of the rest of the little issues if you prefer. Still, I really would like to merge this improvement with tested code to populate the trashed field. Can you help me with this last piece of the puzzle?

Merry Christmas!

Respectfully,
7x

**Comment by se7enxweb** [comment]
@ernestob Apologies for not just merging your contribution, after more thought, it's best to accept it as is and try to improve it soon after. Thank you again for your continued support!

Cheers,
7x

**Pull request merged**
